// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function FetchEmailBody(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchEmailBody'](arg1, arg2, arg3);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetEmailDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEmailDetail'](arg1, arg2, arg3);
}

export function GetEmails(arg1, arg2) {
  return window['go']['main']['App']['GetEmails'](arg1, arg2);
}

export function GetFolders(arg1) {
  return window['go']['main']['App']['GetFolders'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
