// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:main.AddAccountRequest):Promise<main.Account>;

export function DeleteAccount(arg1:string):Promise<void>;

export function FetchEmailBody(arg1:string,arg2:string,arg3:number):Promise<main.EmailDetail>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetEmailDetail(arg1:string,arg2:string,arg3:number):Promise<main.EmailDetail>;

export function GetEmails(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.EmailPage>;

export function GetFolders(arg1:string):Promise<Array<main.Folder>>;

export function SaveAttachment(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function SendEmail(arg1:main.SendRequest):Promise<void>;

export function UpdateAccount(arg1:main.UpdateAccountRequest):Promise<main.Account>;
