// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:main.AddAccountRequest):Promise<main.Account>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function UpdateAccount(arg1:main.UpdateAccountRequest):Promise<main.Account>;
